version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./blog:/usr/src/blog
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://yourusername:yourpassword@db:5432/yourdbname

  alembic:
    build: .
    command: alembic upgrade head
    volumes:
      - ./blog:/usr/src/bog
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://yourusername:yourpassword@db:5432/yourdbname

volumes:
  postgres_data:
